<?php

/**
 * Default Layout
 *  
 * @author
 * @version
 */
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>

	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<?php 
		echo $this->headTitle();
	    echo $this->headScript();
	    echo $this->headStyle();
	    ?>
	</head>
	
	<body>
		<h1><?php echo $this->placeholder('title') ?></h1>
		<?php echo $this->layout()->content ?>

		<br />
		<br />
	</body>

</html>
