<h1>Functions</h1>

<?php if (!count($this->functions)) : ?>
	<p>No functions have been added yet.</p>
<?php else : ?>
	<table>
		<tr>
			<td>&nbsp;</td>
			<td>Title</td>
			<td>Description</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
	<?php foreach($this->functions as $function) : ?>
		<tr>	
			<td>Edit</td>	
			<td><?php echo $function->title; ?></td>
			<td><?php echo $function->description; ?></td>
			<td><a href="<?php echo $this->url(array('controller'=>'index','action'=>'index','id'=>$function->id)); ?>">View Features</a></td>
			<td>Delete</td>
		</tr>
	<?php endforeach; ?>
	</table>
<?php endif; ?>