<div id="welcome">
	<h2>Functions</h2>
	<p><strong>List of functions below:</strong><em></em></p>	
</div>

<div id="example">
	<blockquote>
		<?php if (!count($this->functions)) : ?>
			<p>No functions have been added yet.</p>
		<?php else : ?>
			<table border="0" cellspacing="10" cellpadding="10">
				<tr>
					<td>&nbsp;</td>
          			<td><h3>Title</h3></td>
                    <td><h3>Description</h3></td>			
          			<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr>
			<?php foreach($this->functions as $function) : ?>
				<tr>	
                	<td><a href="<?php echo $this->url(array('controller'=>'functions','action'=>'edit','id'=>$function->id)); ?>">Edit</a></td>	
					<td><?php echo $function->title; ?></td>
					<td><?php echo $function->description; ?></td>
					<td><a href="<?php echo $this->url(array('controller'=>'functions','action'=>'index','id'=>$function->id)); ?>">View Features</a></td>
                    <td><a href="<?php echo $this->url(array('controller'=>'functions','action'=>'delete','id'=>$function->id)); ?>">Delete</a></td>
				</tr>
			<?php endforeach; ?>
			</table>
		<?php endif; ?>
	</blockquote>
</div>		