<h1>Adding a new Feature</h1>
<div id="example">
	<blockquote>
		<form action="#" method="post">
		<table border="0" cellspacing="5" cellpadding="5" width="50%" height="30%">
			<tr>
				<td width="5%">Title</td> 
				<td width="5%">:</td>
				<td width="90%"><input type="text" name="title" size="50"></td>
			</tr>	
			<tr>
				<td>Description</td>
				<td> : </td>
				<td> <input type="text" name="desc" size="50"></td>
			</tr>
			<tr>
				<td align="center" colspan="3"><input type="submit" name="button" id="button" value="Add" /></td>
			</tr>
		</table>
		</form>
	</blockquote>
</div>
