<div id="welcome">
	<h2>Features</h2>
	<p><strong>List of features below:</strong><em></em></p>
</div>

<div id="example">
	<blockquote>
		<?php if (!count($this->features)) : ?>
			<p>No features have been added yet.</p>
		<?php else : ?>                    
			<table border="0" cellspacing="10" cellpadding="10">
				<tr>
                	<td>&nbsp;</td>			
                    <td><h3>Title</h3></td>
                    <td><h3>Description</h3></td>			
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
				<?php foreach($this->features as $feature) : ?>
                <tr>	
                	<td><a href="<?php echo $this->url(array('controller'=>'index','action'=>'edit','id'=>$feature->id)); ?>">Edit</a></td>	
                    <td><?php echo $feature->title; ?></td>
                    <td><?php echo $feature->description; ?></td>
                    <td><a href="<?php echo $this->url(array('controller'=>'functions','action'=>'index','id'=>$feature->id)); ?>">View Functions</a></td>
                    <td><a href="<?php echo $this->url(array('controller'=>'index','action'=>'delete','id'=>$feature->id)); ?>">Delete</a></td>
                </tr>
                <?php endforeach; ?>
			</table>
		<?php endif; ?>
	</blockquote>
</div>