<h1>Features</h1>

<?php if (!count($this->features)) : ?>
	<p>No features have been added yet.</p>
<?php else : ?>
	<table border="0" cellspacing="5" cellpadding="5">
		<tr>
			<td>&nbsp;</td>			
			<td><strong>Title</strong></td>
			<td><strong>Description</strong></td>			
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
	<?php foreach($this->features as $feature) : ?>
		<tr>	
			<td><a href="<?php echo $this->url(array('controller'=>'index','action'=>'edit','id'=>$feature->id)); ?>">Edit</a></td>	
			<td><?php echo $feature->title; ?></td>
			<td><?php echo $feature->description; ?></td>
			<td><a href="<?php echo $this->url(array('controller'=>'functions','action'=>'index','id'=>$feature->id)); ?>">View Functions</a></td>
			<td><a href="<?php echo $this->url(array('controller'=>'index','action'=>'delete','id'=>$feature->id)); ?>">Delete</a></td>
		</tr>
	<?php endforeach; ?>
	</table>
<?php endif; ?>