<?php

/**
 * Default error view
 *  
 * @author
 * @version
 */

//$this->headTitle('Error Page');
//$this->placeholder('title')->set($this->title);
?>
<!--  
<?php if ($this->message): ?>
	<p>The following error occurred:</p>
	<?php echo $this->message ?>
<?php endif; ?>
-->
<h2>Ooops, the site is broken!</h2>
<div>
One of the following may have happened.
<ul>
	<li>You may have typed in the wrong URL.</li>
	<li>You may have followed a bookmark that doesn't exist anymore.</li>
</ul>
</div>
